[package]
name = "socketup"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[[bin]]
name = "socketup-testapp"
path = "src/bin/socketup-testapp.rs"

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
strip = true
codegen-units = 1
